name: "sample demp pipeline creation"
 
on: [workflow_dispatch] #manual trigger 

jobs:
  Self-hosted_Job:
    name: "Self Hosted Job"
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v4
    - name: Echo info about agent to log
      run: |
        echo "this is my first demo"
        echo "Current Directory is `pwd`"
        echo "Operating system details: "
        lsb_release -a
