name: "Sample Demo Pipeline Creation"

on:
  workflow_dispatch: # Manual trigger

jobs:
  self_hosted_job:
    name: "Self Hosted Job"
    runs-on: ubuntu-latest
    steps:
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest           # Optional: specify GCC version
          platform: ubuntu-latest   # Optional: default is x64
          cygwin: false             # Optional: default is false
          g++: true                 # Optional: default is true
          hardlinks: false          # Optional: default is false
